import test from 'node:test';
import assert from 'node:assert/strict';
import { access, mkdir, readFile, symlink, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { initGitRepo, tempWorkspace } from './helpers.mjs';
function run(args){return spawnSync(process.execPath,['scripts/install-into-repo.mjs',...args],{cwd:process.cwd(),encoding:'utf8'});}
test('installer defaults to dry-run and makes no changes',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);const result=run([repo]);assert.equal(result.status,0);assert.match(result.stdout,/DRY_RUN/u);await assert.rejects(()=>access(`${repo}/.forgeai/foundation/package.json`));});
test('installer applies runtime, agents, hooks and ignores volatile state',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);const result=run([repo,'--apply']);assert.equal(result.status,0,result.stderr);await access(`${repo}/.forgeai/foundation/bin/forgeai-foundation.mjs`);await access(`${repo}/.claude/agents/forgeai-writer.md`);await access(`${repo}/.claude/hooks/forgeai-hook.mjs`);const settings=JSON.parse(await readFile(`${repo}/.claude/settings.json`,'utf8'));assert.ok(settings.hooks.PreToolUse.length>0);assert.ok(Object.values(settings.hooks).flatMap(x=>x).flatMap(x=>x.hooks??[]).every(h=>h.command.includes('${CLAUDE_PROJECT_DIR}')));assert.match(await readFile(`${repo}/.gitignore`,'utf8'),/\.forgeai\/runtime\//u);});
test('installer refuses second apply without force',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);assert.equal(run([repo,'--apply']).status,0);assert.notEqual(run([repo,'--apply']).status,0);});
test('installer force replacement removes stale vendored files',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);assert.equal(run([repo,'--apply']).status,0);await writeFile(join(repo,'.forgeai','foundation','stale.txt'),'stale');assert.equal(run([repo,'--apply','--force']).status,0);await assert.rejects(()=>access(join(repo,'.forgeai','foundation','stale.txt')));});
test('installer rejects symlinked settings file',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);await mkdir(join(repo,'.claude'),{recursive:true});const outside=join(repo,'outside.json');await writeFile(outside,'{}');await symlink(outside,join(repo,'.claude','settings.json'));const result=run([repo,'--apply']);assert.notEqual(result.status,0);assert.match(result.stderr,/regular file/u);});
test('installer rejects symlinked control directories',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);const outside=await tempWorkspace('outside-install-');await mkdir(join(repo,'.claude'),{recursive:true});await symlink(outside,join(repo,'.claude','hooks'));const result=run([repo,'--apply']);assert.notEqual(result.status,0);assert.match(result.stderr,/real directory/u);});
