import test from 'node:test';
import assert from 'node:assert/strict';
import { access, mkdir, readFile, symlink, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { initGitRepo, tempWorkspace } from './helpers.mjs';
function run(args){return spawnSync(process.execPath,['scripts/install-into-repo.mjs',...args],{cwd:process.cwd(),encoding:'utf8'});}
test('installer defaults to dry-run and makes no changes',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);const result=run([repo]);assert.equal(result.status,0);assert.match(result.stdout,/DRY_RUN/u);await assert.rejects(()=>access(`${repo}/.forgeai/foundation/package.json`));});
test('installer applies runtime, agents, exec-form hooks and ignores volatile state',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);const result=run([repo,'--apply']);assert.equal(result.status,0,result.stderr);await access(`${repo}/.forgeai/foundation/bin/forgeai-foundation.mjs`);await access(`${repo}/.claude/agents/forgeai-writer.md`);await access(`${repo}/.claude/hooks/forgeai-hook.mjs`);const settings=JSON.parse(await readFile(`${repo}/.claude/settings.json`,'utf8'));const expectedPath='${CLAUDE_PROJECT_DIR}/.claude/hooks/forgeai-hook.mjs';const expectedMatcher='^(?:Edit|Write|NotebookEdit|MultiEdit|Bash|WebFetch|Read|Glob|Grep|LS|mcp__.*)$';for(const[event,entries]of Object.entries(settings.hooks)){for(const entry of entries){if(event==='PreToolUse')assert.equal(entry.matcher,expectedMatcher);for(const hook of entry.hooks??[]){assert.equal(hook.type,'command');assert.equal(hook.command,'node');assert.deepEqual(hook.args,[expectedPath,event]);assert.equal(Object.hasOwn(hook,'shell'),false);}}}assert.match(await readFile(`${repo}/.gitignore`,'utf8'),/\.forgeai\/runtime\//u);});

test('installer preserves unrelated node hooks while adding ForgeAI hook',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);await mkdir(join(repo,'.claude'),{recursive:true});await writeFile(join(repo,'.claude','settings.json'),JSON.stringify({hooks:{SessionStart:[{hooks:[{type:'command',command:'node',args:['custom-hook.mjs'],timeout:5}]}]}}));const result=run([repo,'--apply']);assert.equal(result.status,0,result.stderr);const settings=JSON.parse(await readFile(join(repo,'.claude','settings.json'),'utf8'));const hooks=settings.hooks.SessionStart.flatMap(entry=>entry.hooks??[]);assert.ok(hooks.some(hook=>hook.command==='node'&&JSON.stringify(hook.args)===JSON.stringify(['custom-hook.mjs'])));assert.ok(hooks.some(hook=>hook.command==='node'&&JSON.stringify(hook.args)===JSON.stringify(['${CLAUDE_PROJECT_DIR}/.claude/hooks/forgeai-hook.mjs','SessionStart'])));});

test('installer migrates legacy ForgeAI hook without duplication',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);await mkdir(join(repo,'.claude'),{recursive:true});await writeFile(join(repo,'.claude','settings.json'),JSON.stringify({hooks:{PreToolUse:[{matcher:'Edit|Write',hooks:[{type:'command',command:'node \"${CLAUDE_PROJECT_DIR}/.claude/hooks/forgeai-hook.mjs\" PreToolUse',timeout:15}]}]}}));const result=run([repo,'--apply']);assert.equal(result.status,0,result.stderr);const settings=JSON.parse(await readFile(join(repo,'.claude','settings.json'),'utf8'));const forgeai=settings.hooks.PreToolUse.flatMap(entry=>(entry.hooks??[]).map(hook=>({entry,hook}))).filter(({hook})=>JSON.stringify(hook).includes('forgeai-hook.mjs'));assert.equal(forgeai.length,1);assert.equal(forgeai[0].entry.matcher,'^(?:Edit|Write|NotebookEdit|MultiEdit|Bash|WebFetch|Read|Glob|Grep|LS|mcp__.*)$');assert.equal(forgeai[0].hook.command,'node');assert.deepEqual(forgeai[0].hook.args,['${CLAUDE_PROJECT_DIR}/.claude/hooks/forgeai-hook.mjs','PreToolUse']);});
test('installer refuses second apply without force',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);assert.equal(run([repo,'--apply']).status,0);assert.notEqual(run([repo,'--apply']).status,0);});
test('installer force replacement removes stale vendored files',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);assert.equal(run([repo,'--apply']).status,0);await writeFile(join(repo,'.forgeai','foundation','stale.txt'),'stale');assert.equal(run([repo,'--apply','--force']).status,0);await assert.rejects(()=>access(join(repo,'.forgeai','foundation','stale.txt')));});
test('installer rejects symlinked settings file',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);await mkdir(join(repo,'.claude'),{recursive:true});const outside=join(repo,'outside.json');await writeFile(outside,'{}');await symlink(outside,join(repo,'.claude','settings.json'));const result=run([repo,'--apply']);assert.notEqual(result.status,0);assert.match(result.stderr,/regular file/u);});
test('installer rejects symlinked control directories',async()=>{const repo=await tempWorkspace('install-');await initGitRepo(repo);const outside=await tempWorkspace('outside-install-');await mkdir(join(repo,'.claude'),{recursive:true});await symlink(outside,join(repo,'.claude','hooks'));const result=run([repo,'--apply']);assert.notEqual(result.status,0);assert.match(result.stderr,/real directory/u);});
