import { basename, resolve } from 'node:path';
import { collectRegularFiles } from '../src/file-tree.mjs';
import { readStableRegularFile } from '../src/safe-file.mjs';
import { scanSecrets } from '../src/secret-scan.mjs';
import { readJson } from '../src/utils.mjs';
const findings=[];const pkg=await readJson('package.json');if(pkg.dependencies&&Object.keys(pkg.dependencies).length)findings.push('runtime dependencies must remain empty');if(pkg.devDependencies&&Object.keys(pkg.devDependencies).length)findings.push('development dependencies must remain empty');
const productionFiles=[];for(const directory of ['src','bin','scripts','config','schemas','.claude'])for(const entry of await collectRegularFiles(directory))productionFiles.push(entry.relative.startsWith(`${directory}/`)?entry.relative:`${directory}/${entry.relative}`);
async function text(path,maxBytes=8*1024*1024){return(await readStableRegularFile(resolve(path),{maxBytes})).bytes.toString('utf8');}
for(const path of productionFiles.filter(item=>item.endsWith('.json'))){try{JSON.parse(await text(path));}catch(error){findings.push(`invalid JSON ${path}: ${error.message}`);}}
for(const path of productionFiles.filter(item=>item.endsWith('.mjs'))){const source=await text(path);if(/\beval\s*\(/u.test(source))findings.push(`eval forbidden: ${path}`);if(/\bnew\s+Function\s*\(/u.test(source))findings.push(`new Function forbidden: ${path}`);}
const gateRunner=await text('src/gate-runner.mjs');if(!gateRunner.includes('checkCommand(task,gate.command)')||!gateRunner.includes('shell:false'))findings.push('gate runner must use exact policy and shell:false');
const sonar=await text('scripts/sonar-gate.mjs');if(sonar.includes('-Dsonar.token='))findings.push('Sonar token must not be exposed in process arguments');if(!sonar.includes("shell:false"))findings.push('Sonar scanner must use shell:false');
const sourcePolicy=await text('src/policy.mjs');if(!sourcePolicy.includes("'.claude/hooks/**'"))findings.push('Claude hook files must be protected');if(!sourcePolicy.includes('SHELL_WRAPPERS'))findings.push('shell wrappers must be denied');
const proof=await text('src/proof.mjs');if(!proof.includes("review.final_commit===evidence.final_commit"))findings.push('reviews must be bound to final_commit');
const safeFile=await text('src/safe-file.mjs');if(!safeFile.includes('O_NOFOLLOW'))findings.push('stable file reader must use O_NOFOLLOW');
const fileTree=await text('src/file-tree.mjs');if(!fileTree.includes('directory changed during enumeration'))findings.push('file inventory must detect directory replacement');
for(const entry of await collectRegularFiles('.claude/agents',{include:path=>path.endsWith('.md')})){const source=(await readStableRegularFile(entry.absolute,{maxBytes:1024*1024})).bytes.toString('utf8');const name=basename(entry.relative);const isWriter=name==='forgeai-writer.md';if(!isWriter&&/tools:.*(?:Edit|Write)/u.test(source))findings.push(`read-only profile exposes write tools: ${name}`);if(!isWriter&&!/disallowedTools:.*Edit.*Write/u.test(source)&&name!=='forgeai-orchestrator.md')findings.push(`read-only profile lacks explicit write deny: ${name}`);if(/allow_nested_agents:\s*true/u.test(source))findings.push(`nested agents enabled: ${name}`);}
const settings=await readJson('.claude/settings.fragment.json');const expectedHookPath='${CLAUDE_PROJECT_DIR}/.claude/hooks/forgeai-hook.mjs';const expectedPreToolMatcher='^(?:Edit|Write|NotebookEdit|MultiEdit|Bash|WebFetch|Read|Glob|Grep|LS|mcp__.*)$';for(const[event,entries]of Object.entries(settings.hooks??{})){let forgeaiHooks=0;for(const entry of entries){if(event==='PreToolUse'&&entry.matcher!==expectedPreToolMatcher)findings.push('PreToolUse matcher must be anchored and exact');for(const hook of entry.hooks??[]){forgeaiHooks+=1;if(hook.type!=='command'||hook.command!=='node')findings.push(`hook ${event} must use exec-form node`);if(JSON.stringify(hook.args)!==JSON.stringify([expectedHookPath,event]))findings.push(`hook ${event} args must bind project hook path and event`);if(Object.hasOwn(hook,'shell'))findings.push(`hook ${event} must not declare shell`);}}if(forgeaiHooks!==1)findings.push(`hook ${event} must contain exactly one ForgeAI command hook`);}
const manifest=await readJson('SOURCE_MANIFEST.json',{maxBytes:16*1024*1024});const secretPaths=manifest.files.map(item=>item.path).filter(path=>!path.startsWith('tests/')&&!path.startsWith('examples/')&&path!=='src/secret-scan.mjs'&&path!=='scripts/security-audit.mjs');const secretResult=await scanSecrets('.',{paths:secretPaths});for(const item of secretResult.findings)findings.push(`secret pattern ${item.code} at ${item.path}:${item.line}`);
if(findings.length){process.stderr.write(`${findings.join('\n')}\n`);process.exit(1);}process.stdout.write(`security audit PASS (${productionFiles.length} production files, ${secretResult.files_scanned} secret-scanned files)\n`);
